SistemaDeConsulta/Models/Entities/Paciente.cs
using SistemaDeConsulta.Models.Enums;

namespace SistemaDeConsulta.Models.Entities
{
    public class Paciente
    {
        public int Id { get; set; }
        public string Nome { get; set; }

        public string CPF { get; set; }

        public DateTime DataNascimento { get; set; }

        public SexoEnum Sexo { get; set; }

        public string Telefone { get; set; }

        public string Email { get; set; }
    }
}

SistemaDeConsulta/ViewModels/Pacientes/CreatePacienteViewModel.cs
using SistemaDeConsulta.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace SistemaDeConsulta.ViewModels.Pacientes
{
    public class CreatePacienteViewModel
    {
        public string Nome { get; set; } = string.Empty;

        public string CPF { get; set; } = string.Empty;

        [Display(Name = "Data de Nascimento")]
        public DateTime? DataNascimento { get; set; }

        public SexoEnum Sexo { get; set; }

        public string Telefone { get; set; } = string.Empty;

        public string Email { get; set; } = string.Empty;
    }
}

SistemaDeConsulta/ViewModels/Pacientes/EditPacienteViewModel.cs
using SistemaDeConsulta.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace SistemaDeConsulta.ViewModels.Pacientes
{
    public class EditPacienteViewModel
    {
        public int Id { get; set; }
        public string Nome { get; set; } = string.Empty;

        public string CPF { get; set; } = string.Empty;

        [Display(Name = "Data de Nascimento")]
        [DataType(DataType.Date)]
        public DateTime DataNascimento { get; set; }

        public SexoEnum Sexo { get; set; }

        public string Telefone { get; set; }

        public string Email { get; set; }
    }
}

SistemaDeConsulta/ViewModels/Pacientes/ListPacienteViewModel.cs
using SistemaDeConsulta.Models.Enums;

namespace SistemaDeConsulta.ViewModels.Pacientes
{
    public class ListTipoExamesViewModel
    {
        public int Id { get; set; }
        public string Nome { get; set; } = string.Empty;

        public string CPF { get; set; } = string.Empty;

        public DateTime DataNascimento { get; set; }

        public SexoEnum Sexo { get; set; }

        public string Telefone { get; set; }

        public string Email { get; set; }
    }
}

SistemaDeConsulta/Controllers/PacienteController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SistemaDeConsulta.Data.Context;
using SistemaDeConsulta.Models.Entities;
using SistemaDeConsulta.Models.Enums;
using SistemaDeConsulta.ViewModels.Pacientes;
using System.Text.RegularExpressions;

namespace SistemaDeConsulta.Controllers
{
    public class PacienteController : Controller
    {
        private readonly ApplicationDBContext _dbContext;
        private readonly IValidator<CreatePacienteViewModel> _createPacienteValidator;
        private readonly IValidator<EditPacienteViewModel> _editPacienteValidator;

        public PacienteController(ApplicationDBContext dbContext, IValidator<CreatePacienteViewModel> createPacienteValidator, IValidator<EditPacienteViewModel> editPacienteValidator)
        {
            _dbContext = dbContext;
            _createPacienteValidator = createPacienteValidator;
            _editPacienteValidator = editPacienteValidator;

        }


        public IActionResult Index()
        {
            var pacientes = _dbContext.Pacientes.ToList();

            var viewModelList = pacientes.Select(p => new ListTipoExamesViewModel
            {
                Id = p.Id,
                Nome = p.Nome,
                CPF = p.CPF,
                DataNascimento = p.DataNascimento,
                Sexo = p.Sexo,
                Telefone = p.Telefone,
                Email = p.Email
            }).ToList();

            return View(viewModelList);
        }

 
        public IActionResult Create()
        {
            ViewBag.Sexo = new[]
            {
                new SelectListItem { Text = "Masculino", Value = SexoEnum.Masculino.ToString()},
                new SelectListItem { Text = "Feminino", Value = SexoEnum.Feminino.ToString()},
            };
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreatePacienteViewModel dados)
        {
            try
            {
                var validacao = _createPacienteValidator.Validate(dados);

                if (!validacao.IsValid)
                {
                    ViewBag.Sexo = new[]
                    {
                    new SelectListItem { Text = "Masculino", Value = SexoEnum.Masculino.ToString()},
                    new SelectListItem { Text = "Feminino", Value = SexoEnum.Feminino.ToString()},
                };

                    validacao.AddToModelState(ModelState, string.Empty);
                    return View(dados);
                }

                var paciente = new Paciente
                {
                    Nome = dados.Nome,
                    CPF = Regex.Replace(dados.CPF, "[^0-9]", ""),
                    DataNascimento = dados.DataNascimento as DateTime? ?? DateTime.MinValue,
                    Sexo = dados.Sexo,
                    Telefone = dados.Telefone,
                    Email = dados.Email
                };

                _dbContext.Pacientes.Add(paciente);
                TempData["MensagemSucesso"] = "Paciente cadastrado com sucesso!";
                _dbContext.SaveChanges();

                return RedirectToAction("Index");
            } catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu paciente, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult Edit(int id) 
        {
            var paciente = _dbContext.Pacientes.Find(id);

            if (paciente != null)
            {
                ViewBag.Sexo = new[]
                {
                    new SelectListItem { Text = "Masculino", Value = SexoEnum.Masculino.ToString()},
                    new SelectListItem { Text = "Feminino", Value = SexoEnum.Feminino.ToString()},
                };

                return View(new EditPacienteViewModel
                {
                    Id = paciente.Id,
                    Nome = paciente.Nome,
                    CPF = paciente.CPF,
                    DataNascimento = paciente.DataNascimento,
                    Sexo = paciente.Sexo,
                    Telefone = paciente.Telefone,
                    Email = paciente.Email
                });
            }

            return NotFound();
        }

        [HttpPost]
        public IActionResult Edit(int id, EditPacienteViewModel dados)
        {
            try
            {
                var validacao = _editPacienteValidator.Validate(dados);

                if (!validacao.IsValid)
                {
                    ViewBag.Sexo = new[]
                                    {
                    new SelectListItem { Text = "Masculino", Value = SexoEnum.Masculino.ToString()},
                    new SelectListItem { Text = "Feminino", Value = SexoEnum.Feminino.ToString()},
                };

                    validacao.AddToModelState(ModelState, string.Empty);
                    return View(dados);
                }

                var paciente = _dbContext.Pacientes.Find(id);

                if (paciente != null)
                {
                    paciente.Nome = dados.Nome;
                    paciente.CPF = Regex.Replace(dados.CPF, "[^0-9]", "");
                    paciente.DataNascimento = dados.DataNascimento;
                    paciente.Sexo = dados.Sexo;
                    paciente.Telefone = dados.Telefone;
                    paciente.Email = dados.Email;

                    _dbContext.Pacientes.Update(paciente);
                    TempData["MensagemSucesso"] = "Paciente alterado com sucesso!";
                    _dbContext.SaveChanges();

                    return RedirectToAction("Index");
                }

                return NotFound();
            }
            catch (Exception erro) 
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos alterar seu paciente, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }


        public IActionResult DeleteConfirm(int id)
        {
            var paciente = _dbContext.Pacientes.Find(id);
            return View(paciente);
        }

        public IActionResult Delete(int id)
        {
            try
            {
                var paciente = _dbContext.Pacientes.Find(id);

                if (paciente != null)
                {
                    _dbContext.Pacientes.Remove(paciente);
                    TempData["MensagemSucesso"] = "Paciente excluído com sucesso!";
                    _dbContext.SaveChanges();
                    return RedirectToAction("Index");
                }

                return NotFound();
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos excluir seu paciente, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

SistemaDeConsulta/Views/Paciente/Create.cshtml
@model SistemaDeConsulta.ViewModels.Pacientes.CreatePacienteViewModel;
@using SistemaDeConsulta.Models.Enums

@{
    ViewData["Title"] = "Criar paciente";
}

<div class="text-center">
    <h1 class="display-5">Cadastrar paciente</h1>
</div>

<form asp-action="Create" class="row g-3">
    <div class="col-md-4">
        <label asp-for="Nome" class="form-label"></label>
        <input asp-for="Nome" class="form-control">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="CPF" class="form-label"></label>
        <input asp-for="CPF" class="form-control">
        <span asp-validation-for="CPF" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="DataNascimento" class="form-label"></label>
        <input asp-for="DataNascimento" class="form-control">
        <span asp-validation-for="DataNascimento" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="Sexo" class="form-label">Sexo</label>
        <select asp-for="Sexo" asp-items="@ViewBag.Sexo" class="form-select"></select>
        <span asp-validation-for="Sexo" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="Telefone" class="form-label"></label>
        <input asp-for="Telefone" class="form-control">
        <span asp-validation-for="Telefone" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="Email" class="form-label">E-mail</label>
        <input asp-for="Email" class="form-control">
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="d-flex gap-2 justify-content-md-end">
        <button type="submit" class="btn btn-primary">Adicionar</button>
        <a class="btn btn-secondary" asp-controller="Paciente" asp-action="Index" role="button">Voltar</a>
    </div>
</form>

SistemaDeConsulta/Views/Paciente/DeleteConfirm.cshtml
@using SistemaDeConsulta.Models.Entities;
@model Paciente
@{
    ViewData["Title"] = "Deletar paciente";
}

<div class="text-center">
    <h3>Realmente deseja deletar o paciente (@Model.Nome)?</h3>
    <a role="button" class="btn btn-primary" asp-controller="Paciente" asp-action="Index">Cancelar exclusão</a>
    <a role="button" class="btn btn-danger" asp-controller="Paciente" asp-action="Delete" asp-route-id="@Model.Id">Confirma exclusão</a>
</div>

SistemaDeConsulta/Views/Paciente/Edit.cshtml
@model SistemaDeConsulta.ViewModels.Pacientes.EditPacienteViewModel;
@{
    ViewData["Title"] = "Editar paciente";
}

<div class="text-center">
    <h1 class="display-5">Editar paciente</h1>
</div>

<form asp-action="Edit" class="row g-3">
    <div class="col-md-4">
        <label asp-for="Nome" class="form-label"></label>
        <input asp-for="Nome" class="form-control">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="CPF" class="form-label"></label>
        <input asp-for="CPF" data-val="true" data-val-regex-pattern="^\d{11}$" class="form-control">
        <span asp-validation-for="CPF" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="DataNascimento" class="form-label"></label>
        <input asp-for="DataNascimento" class="form-control">
        <span asp-validation-for="DataNascimento" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="Sexo" class="form-label">Sexo</label>
        <select asp-for="Sexo" asp-items="@ViewBag.Sexo" class="form-select"></select>
        <span asp-validation-for="Sexo" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="Telefone" class="form-label"></label>
        <input asp-for="Telefone" data-val="true" data-val-regex-pattern="^[\s\S]*\S[\s\S]*$" class="form-control">
        <span asp-validation-for="Telefone" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="Email" class="form-label">E-mail</label>
        <input asp-for="Email" data-val="true" data-val-regex-pattern="^[\s\S]*\S[\s\S]*$" class="form-control">
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="d-flex gap-2 justify-content-md-end">
        <button type="submit" class="btn btn-primary">Alterar</button>
        <a class="btn btn-secondary" asp-controller="Paciente" asp-action="Index" role="button">Voltar</a>
    </div>
</form>

SistemaDeConsulta/Views/Paciente/Index.cshtml
@model IEnumerable<SistemaDeConsulta.ViewModels.Pacientes.ListTipoExamesViewModel>;

@{
    ViewData["Title"] = "Lista de pacientes";
}

<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a role="button" class="btn btn-primary" asp-controller="Paciente" asp-action="Create">Adicionar novo paciente</a>
    </div>

    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />
    <h1 class="display-5">Lista de pacientes</h1>

    <div class="table-responsive table-responsive-sm table-responsive-md">
        <table class="table table-striped">
            <thead class="text-start">
                <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">CPF</th>
                    <th scope="col">Data de nascimento</th>
                    <th scope="col">Sexo</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">E-mail</th>
                    <th scope="col" class="text-end"></th>
                </tr>
            </thead>
            <tbody class="text-start">
                @if (Model != null && Model.Any())
                {
                    @foreach (var m in Model)
                    {
                        <tr>
                            <td>@m.Nome</td>
                            <td>@m.CPF</td>
                            <td>@m.DataNascimento.ToString("dd/MM/yyyy")</td>
                            <td>@m.Sexo</td>
                            <td>@m.Telefone</td>
                            <td>@m.Email</td>
                            <td class="text-end">
                                <div class="btn-group" role="group" aria-label="Ações">
                                    <a role="button" class="btn btn-outline-secondary" asp-controller="Paciente" asp-action="Edit" asp-route-id="@m.Id">Editar</a>
                                    <a role="button" type="button" class="btn btn-outline-danger" asp-controller="Paciente" asp-action="DeleteConfirm" asp-route-id="@m.Id">Excluir</a>
                                </div>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr class="odd"><td valign="top" colspan="7">Nenhum paciente encontrado.</td></tr>
                }

            </tbody>
        </table>
    </div>
    
    
</div>