SistemaDeConsulta/Models/Entities/Exame.cs
namespace SistemaDeConsulta.Models.Entities
{
    public class Exame
    {
        public int Id { get; set; }
        public string Nome { get; set; }

        public string Observacoes { get; set; }

        public int TipoExameId { get; set; }

        public TipoExame TipoExame { get; set; }

    }
}

SistemaDeConsulta/ViewModels/Exame/CreateExameViewModel.cs
using SistemaDeConsulta.Models.Entities;
using System.ComponentModel.DataAnnotations;

namespace SistemaDeConsulta.ViewModels.Exame
{
    public class CreateExameViewModel
    {
        public string Nome { get; set; } = string.Empty;

        public string Observacoes { get; set; } = string.Empty;

        [Display(Name = "Tipo de exame")]
        public int TipoExameId { get; set; }

        public TipoExame TipoExame { get; set; }
    }
}

SistemaDeConsulta/ViewModels/Exame/EditExameViewModel.cs
using SistemaDeConsulta.Models.Entities;
using System.ComponentModel.DataAnnotations;

namespace SistemaDeConsulta.ViewModels.Exame
{
    public class EditExameViewModel
    {
        public int Id { get; set; }

        public string Nome { get; set; } = string.Empty;

        public string Observacoes { get; set; } = string.Empty;

        [Display(Name = "Tipo de exame")]
        public int TipoExameId { get; set; }

        public TipoExame TipoExame { get; set; }
    }
}

SistemaDeConsulta/ViewModels/Exame/ListExameViewModel.cs
using SistemaDeConsulta.Models.Entities;

namespace SistemaDeConsulta.ViewModels.Exame
{
    public class ListExameViewModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }

        public string Observacoes { get; set; }

        public string TipoExame { get; set; }
    }
}

SistemaDeConsulta/ViewModels/Exames/CreateExameViewModel.cs
using SistemaDeConsulta.Models.Entities;
using System.ComponentModel.DataAnnotations;

namespace SistemaDeConsulta.ViewModels.Exames
{
    public class CreateExameViewModel
    {
        public string Nome { get; set; } = string.Empty;

        public string Observacoes { get; set; } = string.Empty;

        [Display(Name = "Tipo de exame")]
        public int TipoExameId { get; set; }

        public TipoExame TipoExame { get; set; } = null!;
    }
}

SistemaDeConsulta/ViewModels/Exames/EditExameViewModel.cs
using SistemaDeConsulta.Models.Entities;
using System.ComponentModel.DataAnnotations;

namespace SistemaDeConsulta.ViewModels.Exames
{
    public class EditExameViewModel
    {
        public int Id { get; set; }

        public string Nome { get; set; } = string.Empty;

        public string Observacoes { get; set; } = string.Empty;

        [Display(Name = "Tipo de exame")]
        public int TipoExameId { get; set; }

        public TipoExame TipoExame { get; set; }
    }
}

SistemaDeConsulta/ViewModels/Exames/ListExameViewModel.cs
using SistemaDeConsulta.Models.Entities;

namespace SistemaDeConsulta.ViewModels.Exames
{
    public class ListExameViewModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }

        public string Observacoes { get; set; }

        public string TipoExame { get; set; }
    }
}

SistemaDeConsulta/Controllers/ExameController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaDeConsulta.Data.Context;
using SistemaDeConsulta.Models.Entities;
using SistemaDeConsulta.ViewModels.Exames;

namespace SistemaDeConsulta.Controllers
{
    public class ExameController : Controller
    {
        private readonly ApplicationDBContext _dbContext;
        private readonly IValidator<CreateExameViewModel> _createExameValidator;
        private readonly IValidator<EditExameViewModel> _editExameValidator;

        public ExameController(ApplicationDBContext dbContext, IValidator<CreateExameViewModel> createExameValidator, IValidator<EditExameViewModel> editExameValidator)
        {
            _dbContext = dbContext;
            _createExameValidator = createExameValidator;
            _editExameValidator = editExameValidator;
        }

        public IActionResult Index()
        {
            var exameList = _dbContext.Exames.Include(e => e.TipoExame).ToList();

            var viewModelList = exameList.Select(e => new ListExameViewModel
            {
                Id = e.Id,
                Nome = e.Nome,
                Observacoes = e.Observacoes,
                TipoExame = e.TipoExame.Nome,
            }).ToList();

            return View(viewModelList);
        }

        public IActionResult Create()
        {
            var tiposExame = _dbContext.TipoExames.ToList();

            var tiposExameSelectList = tiposExame.Select(t => new SelectListItem
            {
                Value = t.Id.ToString(),
                Text = t.Nome
            }).ToList();

            ViewBag.TiposExame = tiposExameSelectList;
            return View();
        }

        [HttpPost]
        public IActionResult Create (CreateExameViewModel dados)
        {
            try
            {
                var validacao = _createExameValidator.Validate(dados);

                if (!validacao.IsValid)
                {
                    validacao.AddToModelState(ModelState, string.Empty);

                    var tiposExame = _dbContext.TipoExames.ToList();

                    var tiposExameSelectList = tiposExame.Select(t => new SelectListItem
                    {
                        Value = t.Id.ToString(),
                        Text = t.Nome
                    }).ToList();

                    ViewBag.TiposExame = tiposExameSelectList;

                    return View(dados);
                };

                var exame = new Exame
                {
                    Nome = dados.Nome,
                    Observacoes = dados.Observacoes,
                    TipoExameId = dados.TipoExameId
                };

                _dbContext.Exames.Add(exame);
                TempData["MensagemSucesso"] = "Exame cadastrado com sucesso!";
                _dbContext.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu exame, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult Edit(int id) 
        {
            var exame = _dbContext.Exames.Find(id);
            
            if (exame != null)
            {
                var tiposExame = _dbContext.TipoExames.ToList();

                var tiposExameSelectList = tiposExame.Select(t => new SelectListItem
                {
                    Value = t.Id.ToString(),
                    Text = t.Nome
                }).ToList();

                ViewBag.TiposExame = tiposExameSelectList;

                return View(new EditExameViewModel
                {
                    Id = exame.Id,
                    Nome = exame.Nome,
                    Observacoes = exame.Observacoes,
                    TipoExameId = exame.TipoExameId
                });
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult Edit(int id, EditExameViewModel dados)
        {
            try
            {
                var validacao = _editExameValidator.Validate(dados);
                if (!validacao.IsValid)
                {
                    var tiposExame = _dbContext.TipoExames.ToList();

                    var tiposExameSelectList = tiposExame.Select(t => new SelectListItem
                    {
                        Value = t.Id.ToString(),
                        Text = t.Nome
                    }).ToList();

                    ViewBag.TiposExame = tiposExameSelectList;

                    validacao.AddToModelState(ModelState, string.Empty);
                    return View(dados);

                }

                var exame = _dbContext.Exames.Find(id);

                if (exame != null)
                {
                    exame.Id = dados.Id;
                    exame.Nome = dados.Nome;
                    exame.Observacoes = dados.Observacoes;
                    exame.TipoExameId = dados.TipoExameId;

                    _dbContext.Exames.Update(exame);
                    TempData["MensagemSucesso"] = "Exame alterado com sucesso!";
                    _dbContext.SaveChanges();
                    return RedirectToAction("Index");
                }
                return NotFound();
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos alterar seu exame, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }

        public IActionResult DeleteConfirm(int id)
        {
            var exame = _dbContext.Exames.Find(id);
            return View(exame);
        }

        public IActionResult Delete(int id)
        {
            try
            {
                var exame = _dbContext.Exames.Find(id);

                if (exame != null)
                {
                    _dbContext.Exames.Remove(exame);
                    TempData["MensagemSucesso"] = "Exame excluído com sucesso!";
                    _dbContext.SaveChanges();
                    return RedirectToAction("Index");
                }

                return NotFound();
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos excluir seu exame, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

SistemaDeConsulta/Views/Exame/Create.cshtml
@model SistemaDeConsulta.ViewModels.Exames.CreateExameViewModel;

@{
    ViewData["Title"] = "Criar exame";
}

<div class="text-center">
    <h1 class="display-5">Cadastrar exame</h1>
</div>

<form asp-action="Create" class="row g-3">
    <div class="col-md-4">
        <label asp-for="Nome" class="form-label"></label>
        <input asp-for="Nome" class="form-control">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="Observacoes" class="form-label"></label>
        <input asp-for="Observacoes" class="form-control">
        <span asp-validation-for="Observacoes" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="TipoExameId" class="form-label"></label>
        <select asp-for="TipoExameId" asp-items="@ViewBag.TiposExame" class="form-select"></select>
        <span asp-validation-for="TipoExameId" class="text-danger"></span>
    </div>
    <div class="d-flex gap-2 justify-content-md-end">
        <button type="submit" class="btn btn-primary">Adicionar</button>
        <a class="btn btn-secondary" asp-controller="Exame" asp-action="Index" role="button">Voltar</a>
    </div>
</form>

SistemaDeConsulta/Views/Exame/DeleteConfirm.cshtml
@using SistemaDeConsulta.Models.Entities;
@model Exame
@{
    ViewData["Title"] = "Deletar exame";
}

<div class="text-center">
    <h3>Realmente deseja deletar o exame (@Model.Nome)?</h3>
    <a role="button" class="btn btn-primary" asp-controller="Exame" asp-action="Index">Cancelar exclusão</a>
    <a role="button" class="btn btn-danger" asp-controller="Exame" asp-action="Delete" asp-route-id="@Model.Id">Confirma exclusão</a>
</div>

SistemaDeConsulta/Views/Exame/Edit.cshtml
@model SistemaDeConsulta.ViewModels.Exames.EditExameViewModel;

@{
    ViewData["Title"] = "Editar exame";
}

<div class="text-center">
    <h1 class="display-5">Editar exame</h1>
</div>

<form asp-action="Edit" class="row g-3">
    <div class="col-md-4">
        <label asp-for="Nome" class="form-label"></label>
        <input asp-for="Nome" class="form-control">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="Observacoes" class="form-label"></label>
        <input asp-for="Observacoes" class="form-control">
        <span asp-validation-for="Observacoes" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label asp-for="TipoExameId" class="form-label"></label>
        <select asp-for="TipoExameId" asp-items="@ViewBag.TiposExame" class="form-select"></select>
        <span asp-validation-for="TipoExameId" class="text-danger"></span>
    </div>
    <div class="d-flex gap-2 justify-content-md-end">
        <button type="submit" class="btn btn-primary">Alterar</button>
        <a class="btn btn-secondary" asp-controller="Exame" asp-action="Index" role="button">Voltar</a>
    </div>
</form>

SistemaDeConsulta/Views/Exame/Index.cshtml
@model IEnumerable<SistemaDeConsulta.ViewModels.Exames.ListExameViewModel>;

@{
    ViewData["Title"] = "Lista de exames";
}

<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a role="button" class="btn btn-primary" asp-controller="Exame" asp-action="Create">Adicionar novo exame</a>
    </div>

    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />
    <h1 class="display-5">Lista de exames</h1>

    <div class="table-responsive table-responsive-sm table-responsive-md">
        <table class="table table-striped">
            <thead class="text-start">
                <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">Observações</th>
                    <th scope="col">tipo de exame</th>
                    <th scope="col" class="text-end"></th>
                </tr>
            </thead>
            <tbody class="text-start">
                @if (Model != null && Model.Any())
                {
                    @foreach (var m in Model)
                    {
                        <tr>
                            <td>@m.Nome</td>
                            <td>@m.Observacoes</td>
                            <td>@m.TipoExame</td>
                            <td class="text-end">
                                <div class="btn-group" role="group" aria-label="Ações">
                                    <a role="button" class="btn btn-outline-secondary" asp-controller="Exame" asp-action="Edit" asp-route-id="@m.Id">Editar</a>
                                    <a role="button" type="button" class="btn btn-outline-danger" asp-controller="Exame" asp-action="DeleteConfirm" asp-route-id="@m.Id">Excluir</a>
                                </div>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr class="odd"><td valign="top" colspan="7">Nenhum exame encontrado.</td></tr>
                }

            </tbody>
        </table>
    </div>

</div>