SistemaDeConsulta/Models/Entities/TipoExame.cs
using SistemaDeConsulta.Models.Enums;

namespace SistemaDeConsulta.Models.Entities
{
    public class TipoExame
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
    }
}

SistemaDeConsulta/ViewModels/TipoExames/CreateTipoExamesViewModel.cs
namespace SistemaDeConsulta.ViewModels.TipoExames
{
    public class CreateTipoExamesViewModel
    {
        public string Nome { get; set; } = string.Empty;
        public string Descricao { get; set; } = string.Empty;
    }
}

SistemaDeConsulta/ViewModels/TipoExames/EditTipoExamesViewModel.cs
namespace SistemaDeConsulta.ViewModels.TipoExames
{
    public class EditTipoExamesViewModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
    }
}

SistemaDeConsulta/ViewModels/TipoExames/ListTipoExamesViewModel.cs
namespace SistemaDeConsulta.ViewModels.TipoExames
{
    public class ListTipoExamesViewModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
    }
}

SistemaDeConsulta/Controllers/TipoExameController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Mvc;
using SistemaDeConsulta.Data.Context;
using SistemaDeConsulta.Models.Entities;
using SistemaDeConsulta.ViewModels.TipoExames;

namespace SistemaDeConsulta.Controllers
{
    public class TipoExameController: Controller
    {
        private readonly ApplicationDBContext _dbContext;
        private readonly IValidator<CreateTipoExamesViewModel> _createTipoExameValidator;
        private readonly IValidator<EditTipoExamesViewModel> _editTipoExameValidator;

        public TipoExameController(ApplicationDBContext dbContext, IValidator<CreateTipoExamesViewModel> createTipoExameValidator, IValidator<EditTipoExamesViewModel> editTipoExameValidator)
        {
            _dbContext = dbContext;
            _createTipoExameValidator = createTipoExameValidator;
            _editTipoExameValidator = editTipoExameValidator;
        }
        public IActionResult Index()
        {
            var tipoExame = _dbContext.TipoExames.ToList();

            var viewModelList = tipoExame.Select(p => new ListTipoExamesViewModel
            {
                Id = p.Id,
                Nome = p.Nome,
                Descricao = p.Descricao,
            }).ToList();


            return View(viewModelList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateTipoExamesViewModel dados)
        {
            try
            {
                var validacao = _createTipoExameValidator.Validate(dados);

                if (!validacao.IsValid)
                {
                    validacao.AddToModelState(ModelState, string.Empty);
                    return View(dados);
                }

                var tipoExame = new TipoExame
                {
                    Nome = dados.Nome,
                    Descricao = dados.Descricao
                };

                _dbContext.TipoExames.Add(tipoExame);
                TempData["MensagemSucesso"] = "Tipo exame cadastrado com sucesso!";
                _dbContext.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu tipo de exame, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult Edit(int id)
        {
            var tipoExame = _dbContext.TipoExames.Find(id);
            if (tipoExame != null)
            {

                return View(new EditTipoExamesViewModel
                {
                    Id = tipoExame.Id,
                    Nome = tipoExame.Nome,
                    Descricao = tipoExame.Descricao
                    
                });
            }

            return NotFound();
        }

        [HttpPost]
        public IActionResult Edit(int id, EditTipoExamesViewModel dados)
        {
            try
            {
                var validacao = _editTipoExameValidator.Validate(dados);

                if (!validacao.IsValid)
                {
                    validacao.AddToModelState(ModelState, string.Empty);
                    return View(dados);
                }

                var tipoExame = _dbContext.TipoExames.Find(id);

                if (tipoExame != null)
                {
                    tipoExame.Nome = dados.Nome;
                    tipoExame.Descricao = dados.Descricao;

                    _dbContext.TipoExames.Update(tipoExame);
                    TempData["MensagemSucesso"] = "Tipo exame alterado com sucesso!";
                    _dbContext.SaveChanges();

                    return RedirectToAction("Index");
                }

                return NotFound();
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos alterar seu tipo de exame, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult DeleteConfirm(int id)
        {
            var tipoExame = _dbContext.TipoExames.Find(id);
            return View(tipoExame);
        }

        public IActionResult Delete(int id)
        {
            try
            {
                var tipoExame = _dbContext.TipoExames.Find(id);

                if (tipoExame != null)
                {
                    _dbContext.TipoExames.Remove(tipoExame);
                    TempData["MensagemSucesso"] = "Tipo exame excluído com sucesso!";
                    _dbContext.SaveChanges();
                    return RedirectToAction("Index");
                }

                return NotFound();
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos excluir seu tipo de exame, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }
    }
}

SistemaDeConsulta/Views/TipoExame/Create.cshtml
@model SistemaDeConsulta.ViewModels.TipoExames.CreateTipoExamesViewModel;

@{
    ViewData["Title"] = "Criar Tipo de exame";
}

<div class="text-center">
    <h1 class="display-5">Cadastrar tipo de exame</h1>
</div>

<form asp-action="Create" class="row g-3">
    <div class="col-md-4">
        <label asp-for="Nome" class="form-label"></label>
        <input asp-for="Nome" class="form-control">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="col-md-8">
        <label asp-for="Descricao" class="form-label"></label>
        <textarea  asp-for="Descricao" class="form-control" rows="2"></textarea>
        <span asp-validation-for="Descricao" class="text-danger"></span>
    </div>
        <div class="d-flex gap-2 justify-content-md-end">
        <button type="submit" class="btn btn-primary">Adicionar</button>
        <a class="btn btn-secondary" asp-controller="TipoExame" asp-action="Index" role="button">Voltar</a>
    </div>
</form>

SistemaDeConsulta/Views/TipoExame/DeleteConfirm.cshtml
@using SistemaDeConsulta.Models.Entities;
@model TipoExame
@{
    ViewData["Title"] = "Deletar Tipo de exame";
}

<div class="text-center">
    <h3>Realmente deseja deletar o (@Model.Nome)?</h3>
    <a role="button" class="btn btn-primary" asp-controller="TipoExame" asp-action="Index">Cancelar exclusão</a>
    <a role="button" class="btn btn-danger" asp-controller="TipoExame" asp-action="Delete" asp-route-id="@Model.Id">Confirma exclusão</a>
</div>

SistemaDeConsulta/Views/TipoExame/Edit.cshtml
@model SistemaDeConsulta.ViewModels.TipoExames.EditTipoExamesViewModel;

@{
    ViewData["Title"] = "Editar tipo de exame";
}

<div class="text-center">
    <h1 class="display-5">Editar tipo de exame</h1>
</div>

<form asp-action="Edit" class="row g-3">
    <div class="col-md-4">
        <label asp-for="Nome" class="form-label"></label>
        <input asp-for="Nome" class="form-control">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="col-md-8">
        <label asp-for="Descricao" class="form-label"></label>
        <textarea  asp-for="Descricao" class="form-control" rows="2"></textarea>
        <span asp-validation-for="Descricao" class="text-danger"></span>
    </div>
        <div class="d-flex gap-2 justify-content-md-end">
        <button type="submit" class="btn btn-primary">Alterar</button>
        <a class="btn btn-secondary" asp-controller="TipoExame" asp-action="Index" role="button">Voltar</a>
    </div>
</form>

SistemaDeConsulta/Views/TipoExame/Index.cshtml
@model IEnumerable<SistemaDeConsulta.ViewModels.TipoExames.ListTipoExamesViewModel>;
@{
    ViewData["Title"] = "Lista de tipos de exames";
}

<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a role="button" class="btn btn-primary" asp-controller="TipoExame" asp-action="Create">Adicionar novo tipo de exame</a>
    </div>

    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

    <h1 class="display-5">Lista de tipos de exames</h1>

    <div class="table-responsive table-responsive-sm table-responsive-md">
        <table class="table table-striped">
            <thead class="text-start">
                <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">Descrição</th>
                    <th scope="col" class="text-end"></th>
                </tr>
            </thead>
            <tbody class="text-start">
                @if (Model != null && Model.Any())
                {
                    @foreach (var m in Model)
                    {
                        <tr>
                            <td>@m.Nome</td>
                            <td>@m.Descricao</td>
                            <td class="text-end">
                                <div class="btn-group" role="group" aria-label="Ações">
                                    <a role="button" class="btn btn-outline-secondary" asp-controller="TipoExame" asp-action="Edit" asp-route-id="@m.Id">Editar</a>
                                    <a role="button" type="button" class="btn btn-outline-danger" asp-controller="TipoExame" asp-action="DeleteConfirm" asp-route-id="@m.Id">Excluir</a>
                                </div>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr class="odd"><td valign="top" colspan="5">Nenhum tipo de exame encontrado.</td></tr>
                }
           
            </tbody>
        </table>
    </div>
</div>